insert into TODO_COMPONENT(ID,USERNAME,DESCRIPTION,TARGETDATE,STATE) values(101,'java','Core Java',CURRENT_DATE(),true);

insert into TODO_COMPONENT(ID,USERNAME,DESCRIPTION,TARGETDATE,STATE) values(102,'java','JDBC',CURRENT_DATE(),true);

insert into TODO_COMPONENT(ID,USERNAME,DESCRIPTION,TARGETDATE,STATE) values(103,'java','servlets',CURRENT_DATE(),true);

insert into TODO_COMPONENT(ID,USERNAME,DESCRIPTION,TARGETDATE,STATE) values(104,'java','Hibernate',CURRENT_DATE(),false);

insert into TODO_COMPONENT(ID,USERNAME,DESCRIPTION,TARGETDATE,STATE) values(105,'java','spring',CURRENT_DATE(),false);